### ISSUE TITLE
Upload configuration cache failure report as an artifact

### ISSUE THREAD

**Issue by eygraber** [gradle/gradle-build-action#675] opened 2023-04-16 14:44 UTC
Is it possible for this action to upload the configuration cache report as an artifact? There's sometimes information in it that isn't available in the logs.

**Comment by bigdaz** [comment] 2023-04-25 17:19
At this stage, the action doesn't automatically upload any artifacts from the build. 

The configuration-cache report is not unique in providing useful information not available in the logs. Other examples are the reports produced on CodeNarc or Checkstyle failure.

We have an open-issue (#98) to upload "build reports" in general: this could very easily include the configuration-cache report. A pull request for this functionality would certainly be considered.

In the meantime, you'll need to add a separate step to your workflow to upload the configuration-cache report as an artifact.

(Closing this issue as a duplicate of #98.

**Closed by bigdaz** 2023-04-25 17:19 UTC
