### ISSUE TITLE
Error: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle-build-action#644] opened 2023-03-23 01:56 UTC
https://github.com/LawnchairLauncher/lawnchair/actions/runs/4496194552

```
Failed to save cache entry with path '/home/runner/.gradle/caches/modules-*/files-*/*/*/*/*' and key: dependencies-70dc4f0ec3d1b1cbaf5cee7f6f44e0cc: Error: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
```

**Comment by maciejskorski** [comment] 2023-03-25 13:45
@Goooler  It looks to me that you are trying to create a cache in a place you don't have permissions to. I am experiencing the [same error when trying to cache APT packages](https://github.com/maciejskorski/software_engineering/actions/runs/4519482290)

**Comment by bigdaz** [comment] 2023-04-25 17:34
@Goooler thanks for the report. Looking at the other runs for this workflow, this appears to have been a sporadic problem. I suspect it's an issue with the cache-cleanup not completing it's cleanup prior to the `tar`ing of the cache entries.

I'm going to close this issue since it isn't repeatable and it is not currently actionable. Please comment here if the problem persists, or if you have more details on how to reproduce it.

**Closed by bigdaz** 2023-04-25 17:34 UTC

**Comment by tgrothe** [comment] 2024-02-29 10:53
Hello, we have the same problem in our matrix Windows gradle cache build. The warning appears with every run. As a workaround we have removed the option "cache: gradle".

Please see also:
https://github.com/Dungeon-CampusMinden/Dungeon/blob/4a13e21111e6c0a62d4bb0dfc65e257885ded40c/.github/workflows/github_ci.yml#L22
https://github.com/Dungeon-CampusMinden/Dungeon/issues/1354
https://github.com/Dungeon-CampusMinden/Dungeon/pull/1438
