### ISSUE TITLE
Workflows containing commas in their name fail

### ISSUE THREAD

**Issue by vanshg** [gradle/gradle-build-action#758] opened 2023-06-29 16:51 UTC
After the 2.5.0 release, workflows with commas in their name fail with the error:

```
ValidationError: Key Validation Error: v8-gradle|Linux|Build, test and deploy-build-and-test-code[37a6259cc0c1dae299a7866489dff0bd]-7e6e283daa6662e3fbcaffbf38abebc2169ab560 cannot contain commas.
```

This stems from https://github.com/gradle/gradle-build-action/issues/699

Ideally, the cache should not impose additional restrictions on the Workflow name

**Comment by bigdaz** [comment] 2023-06-29 17:31
Thanks for the report. Closing as a duplicate of #756.

We just released `v2.5.1` which contains a fix for this issue. Using `v2` should now succeed with a workflow name containing a comma.

**Closed by bigdaz** 2023-06-29 17:31 UTC
