### ISSUE TITLE
Unhandled error in Gradle post-action - job will continue

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle-build-action#814] opened 2023-07-21 06:53 UTC
```
Unhandled error in Gradle post-action - job will continue: Error: ENOENT: no such file or directory, realpath '/home/runner/.gradle/caches/8.2.1/scripts/b8760wa39hrc1figg37l7utxc'
```

See this error at https://github.com/Goooler/DemoApp/actions/runs/5619317136

**Comment by yogurtearl** [comment] 2023-08-09 19:52
Possible workaround in this issue: https://github.com/gradle/gradle-build-action/issues/832

**Comment by bigdaz** [comment] 2023-12-12 01:12
Since you have `gradle-home-cache-cleanup` enabled, I'm going to close this as a duplicate of #858

**Closed by bigdaz** 2023-12-12 01:12 UTC
